/** A 3D geographic coordinate: [longitude, latitude, altitude_meters] (SRS §F1.3). */
export type LngLatAlt = [number, number, number];

export interface Station {
  id: number | string;
  /** English name — kept as its own field because it is the fallback everything else leans on. */
  name: string;
  nameTh: string;
  /**
   * Every localised name OpenStreetMap carries for this stop, keyed by
   * language subtag (`en`, `th`, `zh`, `ja`, …). Coverage is real but uneven —
   * see `src/i18n/strings.ts` for the survey — so readers must go through
   * `stationName()` rather than indexing this directly.
   */
  names: Record<string, string>;
  code: string;
  position: LngLatAlt;
}

export type Structure = "elevated" | "atGrade" | "underground";
export type VehicleType = "heavy" | "monorail" | "apm" | "commuter";

/** One line's rendered geometry, generated by tools/fetch-network.mjs. */
export interface LineGeometry {
  key: string;
  name: string;
  nameTh: string;
  color: string;
  structure: Structure;
  vehicleType: VehicleType;
  /** null = track geometry only, never simulated (pre-revenue or absent feed). */
  gtfsRouteId: string | null;
  relationId: number;
  osmName: string;
  track: LngLatAlt[];
  /**
   * Per-track-point structure, parallel to `track` (MVP 6). A line is no
   * longer necessarily uniform: MRT Blue runs in bored tunnel through the core
   * and on viaduct along both outer arms, so `structure` above is only the
   * nominal/fallback value and this is what the renderer splits deck meshes
   * on. Derived from each OSM way's tunnel/bridge tags by
   * tools/track-structure.mjs, applied in tools/fetch-network.mjs.
   */
  trackStructures: Structure[];
  stations: Station[];
}

export interface NetworkData {
  generated: string;
  source: string;
  /** Order is load-bearing: index == cache route_idx == vehicle lane 6. */
  lines: LineGeometry[];
}
