/** A 3D geographic coordinate: [longitude, latitude, altitude_meters] (SRS §F1.3). */
export type LngLatAlt = [number, number, number];

export interface Station {
  id: number | string;
  name: string;
  nameTh: string;
  code: string;
  position: LngLatAlt;
}

export type Structure = "elevated" | "atGrade" | "underground";
export type VehicleType = "heavy" | "monorail" | "apm" | "commuter";

/** One line's rendered geometry, generated by tools/fetch-network.mjs. */
export interface LineGeometry {
  key: string;
  name: string;
  nameTh: string;
  color: string;
  structure: Structure;
  vehicleType: VehicleType;
  /** null = track geometry only, never simulated (pre-revenue or absent feed). */
  gtfsRouteId: string | null;
  relationId: number;
  osmName: string;
  track: LngLatAlt[];
  stations: Station[];
}

export interface NetworkData {
  generated: string;
  source: string;
  /** Order is load-bearing: index == cache route_idx == vehicle lane 6. */
  lines: LineGeometry[];
}
