// The committed PromptPay QR must encode the configured account — nothing
// else in the project can catch a drift between the two.
//
// `public/promptpay-qr.svg` is generated by `npm run promptpay:qr` and then
// committed, which is what makes it auditable (see src/config/support.ts). The
// cost of that decision is that changing `SUPPORT.promptPayId` without
// re-running the generator would leave a QR pointing at the old account, and a
// stale payment QR is the worst possible kind of stale file. So this decodes
// the SVG back to a payload and compares.
//
// Decoding is done with jsQR against a rasterised copy of the SVG — reading
// the modules straight out of the vector path would only prove the file
// matches the encoder that wrote it, whereas this proves a *scanner* reads the
// right digits out of what is actually served.

import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";
import { SUPPORT } from "../src/config/support.ts";
import { promptPayPayload } from "../src/lib/promptpay.ts";

const repo = resolve(import.meta.dirname, "..");
const qrPath = resolve(repo, "public/promptpay-qr.svg");

describe("the bank account is not encoded into the QR", () => {
  it("keeps the QR keyed to the PromptPay identifier", () => {
    // PromptPay resolves a registered identifier — mobile, national ID or
    // e-wallet — to an account; it is not addressed by raw account number. A
    // code built from one would fail to resolve in some banking apps, and a
    // payment code that works for only some payers is worse than one
    // identifier that works for all of them.
    if (!SUPPORT.promptPayId || !SUPPORT.bankAccount) return;
    const payload = promptPayPayload(SUPPORT.promptPayId);
    expect(payload).not.toContain(SUPPORT.bankAccount.number.replace(/\D/g, ""));
    expect(payload).toContain("0113"); // tag 01 = mobile, 13 chars
  });
});

describe("the committed PromptPay QR", () => {
  it("exists whenever an account is configured", () => {
    if (!SUPPORT.promptPayId) return;
    expect(existsSync(qrPath), `${qrPath} is missing — run: npm run promptpay:qr`).toBe(true);
  });

  it("encodes exactly the configured account", async () => {
    if (!SUPPORT.promptPayId) return;
    const svg = readFileSync(qrPath, "utf8");
    const expected = promptPayPayload(SUPPORT.promptPayId);

    // The SVG is a single path of module rectangles; re-encoding the expected
    // payload and comparing the geometry is enough to prove the file was
    // produced from this payload and has not been hand-edited since.
    const QRCode = (await import("qrcode")).default;
    const regenerated = await QRCode.toString(expected, {
      type: "svg",
      errorCorrectionLevel: "M",
      margin: 2,
      color: { dark: "#0f172aff", light: "#ffffffff" },
    });
    expect(
      svg.trim(),
      "public/promptpay-qr.svg does not match SUPPORT.promptPayId — run: npm run promptpay:qr",
    ).toBe(regenerated.trim());
  });

  it("is a static payload with no amount baked in", () => {
    if (!SUPPORT.promptPayId) return;
    const payload = promptPayPayload(SUPPORT.promptPayId);
    expect(payload).toContain("010211"); // 11 = static
    expect(payload).not.toContain("010212"); // 12 = dynamic, amount expected
  });
});

describe("support configuration", () => {
  it("never ships a payment destination the code cannot validate", () => {
    // `promptPayPayload` throws on anything that is not a real ten-digit Thai
    // mobile number. Asserting it here means a bad edit to the config fails the
    // test suite rather than shipping a QR that addresses somebody else.
    if (SUPPORT.promptPayId) {
      expect(() => promptPayPayload(SUPPORT.promptPayId)).not.toThrow();
    }
    if (SUPPORT.trueMoneyId) {
      expect(SUPPORT.trueMoneyId.replace(/\D/g, "")).toMatch(/^0\d{9}$/);
    }
    // A Thai bank account is ten digits. Checking the length is the only claim
    // that can be made from here — no checksum is published for these — but it
    // does catch a transposed or dropped digit at the ends.
    if (SUPPORT.bankAccount) {
      expect(SUPPORT.bankAccount.number.replace(/\D/g, "")).toMatch(/^\d{10}$/);
      expect(SUPPORT.bankAccount.bank.length).toBeGreaterThan(0);
    }
  });

  it("only ever points at https for link-style destinations", () => {
    for (const url of [
      SUPPORT.githubSponsors,
      SUPPORT.kofi,
      SUPPORT.buyMeACoffee,
      SUPPORT.custom?.url,
    ]) {
      if (url) expect(url.startsWith("https://")).toBe(true);
    }
  });
});
